name: Deploy Cloudflare Workers

on:
  release:
    types: [published]

jobs:
  deploy-downloader:
    runs-on: ubuntu-latest
    name: Deploy downloader to production
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: downloader/package-lock.json

      - name: Deploy Downloader Worker
        working-directory: ./downloader
        run: |
          npm i -D wrangler@4
          npx wrangler deploy
          npx wrangler d1 migrations apply tcg-image-metadata-db --remote
          npx wrangler d1 migrations apply tcg-presets-sets-db --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-uploader:
    runs-on: ubuntu-latest
    name: Deploy uploader to production
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: uploader/package-lock.json

      - name: Deploy Uploader Worker
        working-directory: ./uploader
        run: |
          npm i -D wrangler@4
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
