name: Deploy Cloudflare Workers

on:
  push:
#  release:
#    types: [published]

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.worker }} to production
    environment: prod

    strategy:
      matrix:
        worker: [downloader, uploader]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: ./${{ matrix.worker }}/package-lock.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ./${{ matrix.worker }}/.python-version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.worker }}-${{ hashFiles(format('./{0}/uv.lock', matrix.worker)) }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.worker }}-

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Upload secrets to Cloudflare (Uploader only)
        if: matrix.worker == 'uploader'
        run: |
          echo $UPLOADER_TOKEN | wrangler secret put UPLOADER_TOKEN --name uploader
        env:
          UPLOADER_TOKEN: ${{ secrets.UPLOADER_SECRET }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy Worker
        working-directory: ./${{ matrix.worker }}
        run: |
          npm i -D wrangler@4
          uv pip sync uv.lock
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Apply D1 Migrations (Downloader only)
        if: matrix.worker == 'downloader'
        working-directory: ./${{ matrix.worker }}
        run: |
          npx wrangler d1 migrations apply tcg-image-metadata-db --remote
          npx wrangler d1 migrations apply tcg-presets-sets-db --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}